# docker-compose.yml
version: '3.8'

services:
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki-config.yaml

  promtail:
    image: grafana/promtail:2.9.2
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail-config.yaml:/etc/promtail-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./data_source.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"
    depends_on:
      - tempo

  prometheus:
    image: prom/prometheus:v2.55.1
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - NODE_ENV=production
      - OTEL_SERVICE_NAME=nextjs-app
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:14318
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_LOG_LEVEL=debug
    ports:
      - "4000:4000"

  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    ports:
      - "12345:12345"
      - "12346:12346"
      - "14317:14317"
      - "14318:14318"
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
